ACCOUNTS = [ "GCYE7C77EB5AWAA25R5XMWNI2EDOKTTFTTPZKM2SR5DI4B4WFD52DARS", "GA4TDPNUCZPTOHB3TKUYMDCRVATXKEADH7ZEYEBWJKQKE2UBFCYNBPEN", "GARDJZ33FTTLVKGABXDS22SYNTP4VCLYARIEWKMZKYHX3RRLPMNR3HOT"]
VERSION = "0.1.0"
SIGNING_KEY = "GDVHOU4AF2QINLYETV2YFC7YWPRVXN4SKR6SOJZ7LAWODJIZJ7ZPJUER"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
TRANSFER_SERVER = "https://api.anclap.com/transfer6"
TRANSFER_SERVER_SEP0024 = "https://api.anclap.com/transfer24"
WEB_AUTH_ENDPOINT = "https://api.anclap.com/auth"
URI_REQUEST_SIGNING_KEY = "GBUZEC7HXFYQTPSWLJQULHRMEH372KBIMKS4YNBOFNKAYRIZR6MMYJUU"
KYC_SERVER = "https://api.anclap.com/kycserver12"
FEDERATION_SERVER="https://federation.anclap.com/federation"
#DIRECT_PAYMENT_SERVER = "https://api.anclap.com/transfer31"

[[CURRENCIES]]
code="PEN"
issuer="GA4TDPNUCZPTOHB3TKUYMDCRVATXKEADH7ZEYEBWJKQKE2UBFCYNBPEN"
display_decimals=2
name="Sol Digital"
anchor_asset_type="fiat"
anchor_asset="PEN"
is_asset_anchored=true
status="live"
desc="Sol Peruano Digital"
image="https://static.anclap.com/coin/pen.png"
redemption_instructions="Enhanced KYC verification through anclap is required to redeem this asset."

[[CURRENCIES]]
code="ARS"
issuer="GCYE7C77EB5AWAA25R5XMWNI2EDOKTTFTTPZKM2SR5DI4B4WFD52DARS"
display_decimals=2
name="Peso Digital"
anchor_asset_type="fiat"
anchor_asset="ARS"
is_asset_anchored=true
status="live"
desc="Peso Argentino Digital"
image="https://static.anclap.com/coin/ars.png"
redemption_instructions="Enhanced KYC verification through anclap is required to redeem this asset."


[DOCUMENTATION]
ORG_NAME = "Grupo Anchor S.A."
ORG_DBA = "Anclap"
ORG_URL = "https://anclap.com"
ORG_DESCRIPTION = "Fintech Services"
ORG_KEYBASE = "anclap_fintech"
ORG_TWITTER = "AnclapFintech"
ORG_OFFICIAL_EMAIL = "info@anclap.com"
ORG_SUPPORT_EMAIL = "info@anclap.com"


