NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
SIGNING_KEY="GAQJIBVWXUHLD5CSUZDWIQEML7MAGXSS64T6A26SI5CGA33U7ZSYIM54"
TRANSFER_SERVER="https://kbtrading.org/sep6"
TRANSFER_SERVER_SEP0024="https://kbtrading.org/sep24"
WEB_AUTH_ENDPOINT="https://kbtrading.org/auth"
DIRECT_PAYMENT_SERVER="https://kbtrading.org/sep31"
KYC_SERVER = "https://kbtrading.org/kyc"

ACCOUNTS=[
"GDYSPBVZHPQTYMGSYNOHRZQNLB3ZWFVQ2F7EP7YBOLRGD42XIC3QUX5G"
]

[DOCUMENTATION]
ORG_NAME="CLPX S.A."
ORG_URL="https://clpx.finance"
ORG_PHYSICAL_ADDRESS="P.O. Box 2681 Road Town, Tortola BVI"
ORG_OFFICIAL_EMAIL="support@clpx.finance"
ORG_DESCRIPTION="CLPX software created and trades CLPX (Chile PESO COIN)."

[[PRINCIPALS]]
name="Anthony Barker"
email="support@bpventures.us"

[[CURRENCIES]]
code="CLPX"
issuer="GDYSPBVZHPQTYMGSYNOHRZQNLB3ZWFVQ2F7EP7YBOLRGD42XIC3QUX5G"
display_decimals=2
name="Chilean PESO"
desc="Token that displays transactions nominated in Chilean Peso CLP. Cash out and in is supported by CLPX a Chilean company"
anchor_asset_type="fiat"
anchor_asset="CLP"
conditions="Deposits and withdraws take 24 hours"
image="https://kbtrading.org/static/CLPX.200x200.png"
status="live"
is_asset_anchored = true
