VERSION="2.0.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=["GAQRF3UGHBT6JYQZ7YSUYCIYWAF4T2SAA5237Q5LIQYJOHHFAWDXZ7NM","GCY37QZUH2P24CMCTGT2XNMRFSHVQF2DKL4N5VCY22TQ52DFUNEUTKBD"]
SIGNING_KEY="GAHNDAOJ7IB6KKMGKBGI5JWJHCTFXOVGY4U2N57C2CUZPK3SPEPCLU76"
WEB_AUTH_ENDPOINT="https://stellar.mykobo.co/auth"
KYC_SERVER="https://stellar.mykobo.co/kyc"
TRANSFER_SERVER="https://stellar.mykobo.co/sep6"
TRANSFER_SERVER_SEP0024="https://stellar.mykobo.co/sep24"
DIRECT_PAYMENT_SERVER="https://stellar.mykobo.co/sep31"
HOTSWAP_SERVER="https://api.mykobo.co/boomerang"

[DOCUMENTATION]
ORG_NAME="MYKOBO"
ORG_URL="https://mykobo.co"
ORG_LOGO="https://mykobo.co/assets/img/eurc_icon_128.png"
ORG_DESCRIPTION="Set your payments free..."
ORG_PHYSICAL_ADDRESS="Vilnius, Lithuania"
ORG_TWITTER="myk0b0"
ORG_OFFICIAL_EMAIL="hello@mykobo.co"
ORG_SUPPORT_EMAIL="support@mykobo.co"

[[CURRENCIES]]
code="EURC"
issuer="GAQRF3UGHBT6JYQZ7YSUYCIYWAF4T2SAA5237Q5LIQYJOHHFAWDXZ7NM"
is_asset_anchored=true
anchor_asset_type="fiat"
status="live"
anchor_asset="EUR"
display_decimals=2
name="EURo Coin"
desc="Asset backed token pegged 1:1 with the Euro (€)"
image="https://mykobo.co/assets/img/eurc_icon_128.png"
attestation_of_reserve="https://www.mykobo.co/attestations/"