ACCOUNTS = [ "GDKL5TOWWAVLJ2WRAUQS2QJEAGHEDJFXFEPQFB6LKW2WRB257BVLLMT6","GCVVC4SL7G6SCK6AZAHE72RFHZWUFIMAWGAFSKR5VG46GQK6MAFIKX6P"]
VERSION = "0.1.1"
SIGNING_KEY = "GCJ3VWVOQ2WZFFM4G2RWAPORZHESQR4LU536ZR5HTA4CMOWBIWFYXY7S"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
TRANSFER_SERVER = "https://ntokens-box.bpventures.us/sep6"
TRANSFER_SERVER_SEP0024 = "https://ntokens-box.bpventures.us/sep24"
TRANSFER_SERVER_SEP0031 = "https://ntokens-box.bpventures.us/sep31"
WEB_AUTH_ENDPOINT = "https://ntokens-box.bpventures.us/auth"
KYC_SERVER = "https://ntokens-box.bpventures.us/kyc"
DIRECT_PAYMENT_SERVER = "https://ntokens-box.bpventures.us/sep31"

[[CURRENCIES]]
code = "BRL"
issuer = "GDVKY2GU2DRXWTBEYJJWSFXIGBZV6AZNBVVSUHEPZI54LIS6BA7DVVSP"
is_asset_anchored = true
anchor_asset_type = "fiat"
anchor_asset = "BRL"
anchored_asset_type = "fiat"
status = "live"
name = "Brazilian Real"
desc = "Brazilian Real"
image= "https://ntokens.com/img/brl-icon.png"
attestation_of_reserve= "https://ntokens.onlypay.com.br"

[DOCUMENTATION]
ORG_NAME = "nTokens Serviços Digitais Ltda"
ORG_URL = "https://ntokens.com"
ORG_DESCRIPTION = "nTokens - Brazilian Real (BRL) Currency Anchor"
ORG_TWITTER = "ntokens_br"
ORG_GITHUB = "ntokens"
ORG_OFFICIAL_EMAIL = "contact@ntokens.com"
ORG_SUPPORT_EMAIL = "support@ntokens.com"
ORG_PHYSICAL_ADDRESS = "Sao Paulo, SP, Brazil"

